import "~/styles/globals.css";

import { Inter } from "next/font/google";
import { cookies } from "next/headers";

import { TRPCReactProvider } from "~/trpc/react";
import NavigationBar from "./_components/header/navigation-bar";
import HeroWithSearch from "./_components/header/hero/hero-with-search";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`font-sans ${inter.variable}`}>
        <TRPCReactProvider cookies={cookies().toString()}>
          <NavigationBar />
          <main className="mx-auto max-w-7xl space-y-8">{children}</main>
          <footer className="mt-12 w-full p-6 text-center text-sm font-bold text-slate-900/30">
            All Right Reserved &copy; 2023 - {new Date().getFullYear()}
          </footer>
        </TRPCReactProvider>
      </body>
    </html>
  );
}
