import "~/styles/globals.css";

import { Inter } from "next/font/google";
import { cookies } from "next/headers";

import { TRPCReactProvider } from "~/trpc/react";
import NavigationBar from "./_components/header/navigation-bar";
import AlertsProvider from "./_components/ui/alert/alerts-provider";
import Footer from "./_components/footer/footer";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata = {
  title: "Jobify - Find your dream job",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`font-sans ${inter.variable}`}>
        <TRPCReactProvider cookies={cookies().toString()}>
          <AlertsProvider>
            <NavigationBar />
            <main className="mx-auto max-w-7xl space-y-8">{children}</main>
            <Footer />
          </AlertsProvider>
        </TRPCReactProvider>
      </body>
    </html>
  );
}
